name: netlify

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run build and deploy
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        npm ci
        npm run build
        npx netlify deploy
