name: netlify

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run build and deploy
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        yarn install --pure-lockfile
        yarn run build
        ./node_modules/.bin/netlify deploy
